done

diff --git a/0x0C-web_server/0-transfer-file b/0x0C-web_server/0-transfer-file
--- a/0x0C-web_server/0-transfer-file
+++ b/0x0C-web_server/0-transfer-file
@@ -1,18 +1,27 @@
 #!/usr/bin/env bash
-# Transfer file `file` to a server
-#scp /path/to/file username@a:/path/to/destination
+# checking for command line arguments
 
-#If number of arguments is >= 3
-if [ $# -ge 3 ]
+if [ $# -lt 4 ]
 then
-    if [ $# -eq 3 ]
-    then
-        # No private key provided
-        scp -o StrictHostKeyChecking=no $1 $3@$2:~/ 
-    else
-        # Private key provided
-        scp -o StrictHostKeyChecking=no -i $4 $1 $3@$2:~/
-    fi
+	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+	exit 1
+fi
+
+# assigning parameters to variables
+
+path_to_file=$1
+ip=$2
+username=$3
+path_to_ssh_key=$4
+
+# disabbling strict host key checking
+
+scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
+
+# checking if the transfer was successful
+if [ $? -eq 0 ]
+then
+	echo "File was transfered successfully"
 else
-    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+	echo "File transfer failed"
 fi
